version: '3'

services:
  web:
    image: ai-server
    build: .
    environment:
      DB_URL: jdbc:postgresql://database:5432/ai-database
    depends_on:
      - database
    ports:
      - "80:8080"
    networks:
      - inner

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: ai-database
    ports:
      - "5432:5432"
    networks:
      - inner

networks:
  inner:
    driver: bridge